"use client"

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'PT-BR' | 'EN' | 'ES';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
    'EN': {
        'Feed': 'Feed',
        'Community': 'Community',
        'Courses': 'Courses',
        'Calendar': 'Calendar',
        'Pages': 'Pages',
        'Account': 'Account',
        'Profile': 'Profile',
        'Settings': 'Settings',
        'Logout': 'Logout',
        'Admin Dashboard': 'Admin Dashboard',
        'Create New Space': 'Create New Space',
        'All Courses': 'All Courses',
        'Search': 'Search',
        'My Account': 'My Account',
        'Support': 'Support',
        'Personal Information': 'Personal Information',
        'Subscription': 'Subscription',
        'Save Changes': 'Save Changes',
        'Name': 'Name',
        'Surname': 'Surname',
        'Email': 'Email',
        'Phone': 'Phone',
        'Bio': 'Bio',
        'Country': 'Country',
        'City': 'City',
        'Current Password': 'Current Password',
        'New Password': 'New Password',
        'Confirm New Password': 'Confirm New Password',
        'Notifications': 'Notifications',
        'Notify by WhatsApp': 'Notify by WhatsApp',
        'Notify by Email': 'Notify by Email',
        'Platform Access': 'Platform Access',
        'Subscription expires on': 'Subscription expires on',
        'Active': 'Active',
        'Expired': 'Expired',
        'No active platform subscription.': 'No active platform subscription.',
        'Course Enrollments': 'Course Enrollments',
        'Enrolled on': 'Enrolled on',
        'No active course enrollments found.': 'No active course enrollments found.',
        'Renew now with discount!': 'Renew now with discount!',
        'Likes': 'Likes',
        'New post': 'New post',
        'Trending posts': 'Trending posts',
        'Upcoming events': 'Upcoming events',
        'No upcoming events.': 'No upcoming events.',
        'No trending posts yet.': 'No trending posts yet.',
        'Community Hub': 'Community Hub',
        'COMMUNITY RULES': 'COMMUNITY RULES',
        'BE RESPECTFUL': 'BE RESPECTFUL',
        'This community is built on integrity and mutual support. Treat everyone with respect.': 'This community is built on integrity and mutual support. Treat everyone with respect.',
        'No spam, no hate speech, and no self-promotion without permission.': 'No spam, no hate speech, and no self-promotion without permission.',
        'Like': 'Like',
        'Comment': 'Comment',
        'You still have': 'You still have',
        'days of access': 'days of access',
        'Access expired': 'Access expired',
        'My Courses': 'My Courses',
        'Manage Courses': 'Manage Courses',
        'Create Course': 'Create Course',
        'Edit Content': 'Edit Content',
        'Delete Course': 'Delete Course',
        'Start Learning': 'Start Learning',
        'Continue Learning': 'Continue Learning',
        'Progress': 'Progress',
        'Lessons': 'Lessons',
        'Certificate': 'Certificate',
        'Materials': 'Materials',
        'Powered by': 'Powered by',
        'Loading courses...': 'Loading courses...',
        // New translations
        'Loading...': 'Loading...',
        'Title': 'Title',
        'Description': 'Description',
        'Content': 'Content',
        'Design': 'Design',
        'Banner': 'Banner',
        'Thumbnail': 'Thumbnail',
        'Slug (URL)': 'Slug (URL)',
        'Spaces': 'Spaces',
        'Bookmarks': 'Bookmarks',
        'Messages': 'Messages',
        'No notifications': 'No notifications',
        'Mark all as read': 'Mark all as read',
        'No results found.': 'No results found.',
        'No courses found. Create your first course!': 'No courses found. Create your first course!',
        'Change Password': 'Change Password',
        'Update your personal details and password.': 'Update your personal details and password.',
        'Create and manage your educational content.': 'Create and manage your educational content.',
        'Changes saved successfully': 'Changes saved successfully',
        'Includes Certificate': 'Includes Certificate',
        'Enable Certificate': 'Enable Certificate',
        'Issue automatically on completion': 'Issue automatically on completion',
        'Enable certificates to configure the design.': 'Enable certificates to configure the design.',
        'Choose Template': 'Choose Template',
        'Custom Background Image': 'Custom Background Image',
        'Overrides template background. Recommended: 2000x1414px': 'Overrides template background. Recommended: 2000x1414px',
        'Certificate Title': 'Certificate Title',
        'Body Text': 'Body Text',
        'Completed the course successfully': 'Completed the course successfully',
        'Appears after the student name.': 'Appears after the student name.',
        'Signer Name': 'Signer Name',
        'Live Preview': 'Live Preview',
        'View your active enrollments and plans.': 'View your active enrollments and plans.',
        // New Admin & Sidebar Keys
        'Manage Groups': 'Manage Groups',
        'Manage Users': 'Manage Users',
        'Users Management': 'Users Management',
        'View users and manage enrollments.': 'View users and manage enrollments.',
        'Create User': 'Create User',
        'Total Users': 'Total Users',
        'Search by name or email...': 'Search by name or email...',
        'Joined': 'Joined',
        'Subscription Ends': 'Subscription Ends',
        'Enroll': 'Enroll',
        'Reset Pass': 'Reset Pass',
        'Create New User': 'Create New User',
        'Manually create a user. Subscription Expiration Date is mandatory.': 'Manually create a user. Subscription Expiration Date is mandatory.',
        'WhatsApp (Optional)': 'WhatsApp (Optional)',
        'Subscription Expiration Date': 'Subscription Expiration Date',
        'Cancel': 'Cancel',
        'Enroll User': 'Enroll User',
        'Manually enroll': 'Manually enroll',
        'in a course.': 'in a course.',
        'Select Course': 'Select Course',
        'Select a course': 'Select a course',
        'Duration (Days)': 'Duration (Days)',
        'Confirm Enrollment': 'Confirm Enrollment',
        // Settings & Dashboard Keys
        'Saving...': 'Saving...',
        'Change your access password': 'Change your access password',
        'Language / Idioma': 'Language / Idioma',
        'Choose interface language': 'Choose interface language',
        'Portuguese': 'Portuguese',
        'English': 'English',
        'Spanish': 'Spanish',
        'Configure your notification preferences': 'Configure your notification preferences',
        'Email Notifications': 'Email Notifications',
        'Receive updates via email': 'Receive updates via email',
        'Push Notifications': 'Push Notifications',
        'Receive browser notifications': 'Receive browser notifications',
        'Profile updated successfully': 'Profile updated successfully',
        'Error updating profile': 'Error updating profile',
        'Passwords do not match': 'Passwords do not match',
        'New password must be at least 6 characters': 'New password must be at least 6 characters',
        'Password changed successfully!': 'Password changed successfully!',
        'Error changing password': 'Error changing password',
        'Good morning': 'Good morning',
        'Good afternoon': 'Good afternoon',
        'Good evening': 'Good evening',
        'Continue your learning journey': 'Continue your learning journey',
        'days of streak!': 'days of streak!',
        'All': 'All',
        'Trending': 'Trending',
        'What do you want to share?': 'What do you want to share?',
        'Create Post': 'Create Post',
        'Title (optional)': 'Title (optional)',
        'What do you want to share with the community?': 'What do you want to share with the community?',
        'Publish': 'Publish',
        'No posts yet. Be the first to share!': 'No posts yet. Be the first to share!',
        'Popular': 'Popular',
        'No courses in progress.': 'No courses in progress.',
        'Completed Courses': 'Completed Courses',
        '100% Completed': '100% Completed',
        'Recommended': 'Recommended',
        'Points Ranking': 'Points Ranking',
        'No ranking available.': 'No ranking available.',
        'Your Achievements': 'Your Achievements',
        'No achievements yet.': 'No achievements yet.',
        'Change Avatar': 'Change Avatar',
        'Receive updates and reminders via WhatsApp': 'Receive updates and reminders via WhatsApp',
        'Receive updates and newsletters via Email': 'Receive updates and newsletters via Email',
        'Avatar updated': 'Avatar updated',
        'Failed to update avatar': 'Failed to update avatar',
        'Are you sure you want to delete this course?': 'Are you sure you want to delete this course?',
        'Failed to delete course': 'Failed to delete course',
        'Start a post...': 'Start a post...',
        'Posting in space': 'Posting in space',
        'Choose a space': 'Choose a space',
        'Comments': 'Comments',
        'Write a comment...': 'Write a comment...',
        'Send': 'Send',
        'No completed courses yet.': 'No completed courses yet.',
        'In Progress': 'In Progress',
        'Community Feed': 'Community Feed',
        'View all': 'View all',
    },
    'PT-BR': {
        'Feed': 'Feed',
        'Community': 'Comunidade',
        'Courses': 'Cursos',
        'Calendar': 'Calendário',
        'Pages': 'Páginas',
        'Account': 'Conta',
        'Profile': 'Perfil',
        'Settings': 'Configurações',
        'Logout': 'Sair',
        'Admin Dashboard': 'Painel Admin',
        'Create New Space': 'Criar Novo Espaço',
        'All Courses': 'Todos os Cursos',
        'Search': 'Pesquisar',
        'My Account': 'Minha Conta',
        'Support': 'Suporte',
        'Personal Information': 'Informações Pessoais',
        'Subscription': 'Assinatura',
        'Save Changes': 'Salvar Alterações',
        'Name': 'Nome',
        'Surname': 'Sobrenome',
        'Email': 'E-mail',
        'Phone': 'Telefone',
        'Bio': 'Biografia',
        'Country': 'País',
        'City': 'Cidade',
        'Current Password': 'Senha Atual',
        'New Password': 'Nova Senha',
        'Confirm New Password': 'Confirmar Nova Senha',
        'Notifications': 'Notificações',
        'Notify by WhatsApp': 'Notificar por WhatsApp',
        'Notify by Email': 'Notificar por E-mail',
        'Platform Access': 'Acesso à Plataforma',
        'Subscription expires on': 'Assinatura expira em',
        'Active': 'Ativo',
        'Expired': 'Expirado',
        'No active platform subscription.': 'Nenhuma assinatura ativa.',
        'Course Enrollments': 'Matrículas em Cursos',
        'Enrolled on': 'Matriculado em',
        'No active course enrollments found.': 'Nenhuma matrícula encontrada.',
        'Renew now with discount!': 'Renove agora com desconto!',
        'Likes': 'Curtidas',
        'New post': 'Nova publicação',
        'Trending posts': 'Em alta',
        'Upcoming events': 'Próximos eventos',
        'No upcoming events.': 'Nenhum evento próximo.',
        'No trending posts yet.': 'Nenhuma publicação em alta.',
        'Community Hub': 'Central da Comunidade',
        'COMMUNITY RULES': 'REGRAS DA COMUNIDADE',
        'BE RESPECTFUL': 'SEJA RESPEITOSO',
        'This community is built on integrity and mutual support. Treat everyone with respect.': 'Esta comunidade é construída com integridade e apoio mútuo. Trate todos com respeito.',
        'No spam, no hate speech, and no self-promotion without permission.': 'Sem spam, discurso de ódio ou autopromoção sem permissão.',
        'Like': 'Curtir',
        'Comment': 'Comentar',
        'You still have': 'Você ainda tem',
        'days of access': 'dias de acesso',
        'Access expired': 'Acesso expirado',
        'My Courses': 'Meus Cursos',
        'Manage Courses': 'Administrar Cursos',
        'Create Course': 'Criar Curso',
        'Edit Content': 'Editar Conteúdo',
        'Delete Course': 'Excluir Curso',
        'Start Learning': 'Iniciar Curso',
        'Continue Learning': 'Continuar Curso',
        'Progress': 'Progresso',
        'Lessons': 'Aulas',
        'Certificate': 'Certificado',
        'Materials': 'Materiais',
        'Powered by': 'Desenvolvido por',
        'Loading courses...': 'Carregando cursos...',
        // New translations
        'Loading...': 'Carregando...',
        'Title': 'Título',
        'Description': 'Descrição',
        'Content': 'Conteúdo',
        'Design': 'Design',
        'Banner': 'Banner',
        'Thumbnail': 'Miniatura',
        'Slug (URL)': 'Slug (URL)',
        'Spaces': 'Espaços',
        'Bookmarks': 'Favoritos',
        'Messages': 'Mensagens',
        'No notifications': 'Sem notificações',
        'Mark all as read': 'Marcar todas como lidas',
        'No results found.': 'Nenhum resultado encontrado.',
        'No courses found. Create your first course!': 'Nenhum curso encontrado. Crie seu primeiro curso!',
        'Change Password': 'Alterar Senha',
        'Update your personal details and password.': 'Atualize seus dados pessoais e senha.',
        'Create and manage your educational content.': 'Crie e gerencie seu conteúdo educacional.',
        'Changes saved successfully': 'Alterações salvas com sucesso',
        'Includes Certificate': 'Inclui Certificado',
        'Enable Certificate': 'Habilitar Certificado',
        'Issue automatically on completion': 'Emitir automaticamente ao concluir',
        'Enable certificates to configure the design.': 'Habilite certificados para configurar o design.',
        'Choose Template': 'Escolher Modelo',
        'Custom Background Image': 'Imagem de Fundo Personalizada',
        'Overrides template background. Recommended: 2000x1414px': 'Substitui o fundo do modelo. Recomendado: 2000x1414px',
        'Certificate Title': 'Título do Certificado',
        'Body Text': 'Texto do Corpo',
        'Completed the course successfully': 'Completou com êxito o curso',
        'Appears after the student name.': 'Aparece após o nome do aluno.',
        'Signer Name': 'Nome do Assinante',
        'Live Preview': 'Visualização ao Vivo',
        'View your active enrollments and plans.': 'Visualize suas matrículas e planos ativos.',
        // New Admin & Sidebar Keys
        'Manage Groups': 'Administrar Grupos',
        'Manage Users': 'Gerenciar Usuários',
        'Users Management': 'Gerenciamento de Usuários',
        'View users and manage enrollments.': 'Visualize usuários e gerencie matrículas.',
        'Create User': 'Criar Usuário',
        'Total Users': 'Total de Usuários',
        'Search by name or email...': 'Buscar por nome ou email...',
        'Joined': 'Entrou',
        'Subscription Ends': 'Fim da Assinatura',
        'Enroll': 'Matricular',
        'Reset Pass': 'Resetar Senha',
        'Create New User': 'Criar Novo Usuário',
        'Manually create a user. Subscription Expiration Date is mandatory.': 'Criar usuário manualmente. Data de expiração obrigatória.',
        'WhatsApp (Optional)': 'WhatsApp (Opcional)',
        'Subscription Expiration Date': 'Data de Expiração',
        'Cancel': 'Cancelar',
        'Enroll User': 'Matricular Usuário',
        'Manually enroll': 'Matricular manualmente',
        'in a course.': 'em um curso.',
        'Select Course': 'Selecionar Curso',
        'Select a course': 'Selecione um curso',
        'Duration (Days)': 'Duração (Dias)',
        'Confirm Enrollment': 'Confirmar Matrícula',
        // Settings & Dashboard Keys
        'Saving...': 'Salvando...',
        'Change your access password': 'Altere sua senha de acesso',
        'Language / Idioma': 'Idioma / Language',
        'Choose interface language': 'Escolha o idioma da interface',
        'Portuguese': 'Português',
        'English': 'Inglês',
        'Spanish': 'Espanhol',
        'Configure your notification preferences': 'Configure suas preferências de notificação',
        'Email Notifications': 'Notificações por Email',
        'Receive updates via email': 'Receba atualizações por email',
        'Push Notifications': 'Notificações Push',
        'Receive browser notifications': 'Receba notificações no navegador',
        'Profile updated successfully': 'Perfil atualizado com sucesso',
        'Error updating profile': 'Erro ao atualizar perfil',
        'Passwords do not match': 'As senhas não coincidem',
        'New password must be at least 6 characters': 'A nova senha deve ter pelo menos 6 caracteres',
        'Password changed successfully!': 'Senha alterada com sucesso!',
        'Error changing password': 'Erro ao alterar senha',
        'Good morning': 'Bom dia',
        'Good afternoon': 'Boa tarde',
        'Good evening': 'Boa noite',
        'Continue your learning journey': 'Continue sua jornada de aprendizado',
        'days of streak!': 'dias de sequência!',
        'All': 'Todos',
        'Trending': 'Em Alta',
        'What do you want to share?': 'O que você quer compartilhar?',
        'Create Post': 'Criar Publicação',
        'Title (optional)': 'Título (opcional)',
        'What do you want to share with the community?': 'O que você quer compartilhar com a comunidade?',
        'Publish': 'Publicar',
        'No posts yet. Be the first to share!': 'Nenhuma publicação ainda. Seja o primeiro a compartilhar!',
        'Popular': 'Popular',
        'No courses in progress.': 'Nenhum curso em andamento.',
        'Completed Courses': 'Cursos Concluídos',
        '100% Completed': '100% Concluído',
        'Recommended': 'Recomendados',
        'Points Ranking': 'Ranking de Pontos',
        'No ranking available.': 'Nenhum ranking disponível.',
        'Your Achievements': 'Suas Conquistas',
        'No achievements yet.': 'Nenhuma conquista ainda.',
        'Change Avatar': 'Alterar Avatar',
        'Receive updates and reminders via WhatsApp': 'Receber atualizações e lembretes via WhatsApp',
        'Receive updates and newsletters via Email': 'Receber atualizações e novidades via E-mail',
        'Avatar updated': 'Avatar atualizado',
        'Failed to update avatar': 'Falha ao atualizar avatar',
        'Are you sure you want to delete this course?': 'Tem certeza que deseja excluir este curso?',
        'Failed to delete course': 'Falha ao excluir curso',
        'Start a post...': 'Começar uma publicação...',
        'Posting in space': 'Publicando no espaço',
        'Choose a space': 'Escolher um espaço',
        'Comments': 'Comentários',
        'Write a comment...': 'Escreva um comentário...',
        'Send': 'Enviar',
        'No completed courses yet.': 'Nenhum curso concluído ainda.',
        'In Progress': 'Em Progresso',
        'Community Feed': 'Feed da Comunidade',
        'View all': 'Ver todos',
    },
    'ES': {
        'Feed': 'Inicio',
        'Community': 'Comunidad',
        'Courses': 'Cursos',
        'Calendar': 'Calendario',
        'Pages': 'Páginas',
        'Account': 'Cuenta',
        'Profile': 'Perfil',
        'Settings': 'Configuración',
        'Logout': 'Cerrar sesión',
        'Admin Dashboard': 'Panel de Admin',
        'Create New Space': 'Crear Nuevo Espacio',
        'All Courses': 'Todos los Cursos',
        'Search': 'Buscar',
        'My Account': 'Mi Cuenta',
        'Support': 'Soporte',
        'Personal Information': 'Información Personal',
        'Subscription': 'Suscripción',
        'Save Changes': 'Guardar Cambios',
        'Name': 'Nombre',
        'Surname': 'Apellido',
        'Email': 'Correo electrónico',
        'Phone': 'Teléfono',
        'Bio': 'Biografía',
        'Country': 'País',
        'City': 'Ciudad',
        'Current Password': 'Contraseña Actual',
        'New Password': 'Nueva Contraseña',
        'Confirm New Password': 'Confirmar Nueva Contraseña',
        'Notifications': 'Notificaciones',
        'Notify by WhatsApp': 'Notificar por WhatsApp',
        'Notify by Email': 'Notificar por Correo',
        'Platform Access': 'Acceso a la Plataforma',
        'Subscription expires on': 'La suscripción expira el',
        'Active': 'Activo',
        'Expired': 'Expirado',
        'No active platform subscription.': 'Sin suscripción activa.',
        'Course Enrollments': 'Inscripciones a Cursos',
        'Enrolled on': 'Inscrito el',
        'No active course enrollments found.': 'No se encontraron inscripciones.',
        'Renew now with discount!': '¡Renueva ahora con descuento!',
        'Likes': 'Me gusta',
        'New post': 'Nueva publicación',
        'Trending posts': 'Tendencias',
        'Upcoming events': 'Próximos eventos',
        'No upcoming events.': 'No hay eventos próximos.',
        'No trending posts yet.': 'Aún no hay publicaciones en tendencia.',
        'Community Hub': 'Centro de Comunidad',
        'COMMUNITY RULES': 'REGLAS DE LA COMUNIDAD',
        'BE RESPECTFUL': 'SÉ RESPETUOSO',
        'This community is built on integrity and mutual support. Treat everyone with respect.': 'Esta comunidad se basa en la integridad y el apoyo mutuo. Trata a todos con respeto.',
        'No spam, no hate speech, and no self-promotion without permission.': 'Sin spam, discurso de odio ni autopromoción sin permiso.',
        'Like': 'Me gusta',
        'Comment': 'Comentar',
        'You still have': 'Aún tienes',
        'days of access': 'días de acceso',
        'Access expired': 'Acceso expirado',
        'My Courses': 'Mis Cursos',
        'Manage Courses': 'Administrar Cursos',
        'Create Course': 'Crear Curso',
        'Edit Content': 'Editar Contenido',
        'Delete Course': 'Eliminar Curso',
        'Start Learning': 'Iniciar Curso',
        'Continue Learning': 'Continuar Curso',
        'Progress': 'Progreso',
        'Lessons': 'Clases',
        'Certificate': 'Certificado',
        'Materials': 'Materiales',
        'Powered by': 'Desarrollado por',
        'Loading courses...': 'Cargando cursos...',
        // New translations
        'Loading...': 'Cargando...',
        'Title': 'Título',
        'Description': 'Descripción',
        'Content': 'Contenido',
        'Design': 'Diseño',
        'Banner': 'Banner',
        'Thumbnail': 'Miniatura',
        'Slug (URL)': 'Slug (URL)',
        'Spaces': 'Espacios',
        'Bookmarks': 'Marcadores',
        'Messages': 'Mensajes',
        'No notifications': 'Sin notificaciones',
        'Mark all as read': 'Marcar todas como leídas',
        'No results found.': 'No se encontraron resultados.',
        'No courses found. Create your first course!': 'No se encontraron cursos. ¡Crea tu primer curso!',
        'Change Password': 'Cambiar Contraseña',
        'Update your personal details and password.': 'Actualiza tus datos personales y contraseña.',
        'Create and manage your educational content.': 'Crea y administra tu contenido educativo.',
        'Changes saved successfully': 'Cambios guardados exitosamente',
        'Includes Certificate': 'Incluye Certificado',
        'Enable Certificate': 'Habilitar Certificado',
        'Issue automatically on completion': 'Emitir automáticamente al completar',
        'Enable certificates to configure the design.': 'Habilita certificados para configurar el diseño.',
        'Choose Template': 'Elegir Plantilla',
        'Custom Background Image': 'Imagen de Fondo Personalizada',
        'Overrides template background. Recommended: 2000x1414px': 'Reemplaza el fondo de la plantilla. Recomendado: 2000x1414px',
        'Certificate Title': 'Título del Certificado',
        'Body Text': 'Texto del Cuerpo',
        'Completed the course successfully': 'Completó con éxito el curso',
        'Appears after the student name.': 'Aparece después del nombre del estudiante.',
        'Signer Name': 'Nombre del Firmante',
        'Live Preview': 'Vista Previa en Vivo',
        'View your active enrollments and plans.': 'Ver sus inscripciones y planes activos.',
        // New Admin & Sidebar Keys
        'Manage Groups': 'Administrar Grupos',
        'Manage Users': 'Administrar Usuarios',
        'Users Management': 'Gestión de Usuarios',
        'View users and manage enrollments.': 'Ver usuarios y gestionar inscripciones.',
        'Create User': 'Crear Usuario',
        'Total Users': 'Usuarios Totales',
        'Search by name or email...': 'Buscar por nombre o correo...',
        'Joined': 'Unido',
        'Subscription Ends': 'Suscripción Termina',
        'Enroll': 'Inscribir',
        'Reset Pass': 'Restablecer Clave',
        'Create New User': 'Crear Nuevo Usuario',
        'Manually create a user. Subscription Expiration Date is mandatory.': 'Crear usuario manualmente. Fecha de expiración obligatoria.',
        'WhatsApp (Optional)': 'WhatsApp (Opcional)',
        'Subscription Expiration Date': 'Fecha de Expiración',
        'Cancel': 'Cancelar',
        'Enroll User': 'Inscribir Usuario',
        'Manually enroll': 'Inscribir manualmente',
        'in a course.': 'en un curso.',
        'Select Course': 'Seleccionar Curso',
        'Select a course': 'Seleccione un curso',
        'Duration (Days)': 'Duración (Días)',
        'Confirm Enrollment': 'Confirmar Inscripción',
        // Settings & Dashboard Keys
        'Saving...': 'Guardando...',
        'Change your access password': 'Cambie su contraseña de acceso',
        'Language / Idioma': 'Idioma / Language',
        'Choose interface language': 'Elija el idioma de la interfaz',
        'Portuguese': 'Portugués',
        'English': 'Inglés',
        'Spanish': 'Español',
        'Configure your notification preferences': 'Configure sus preferencias de notificación',
        'Email Notifications': 'Notificaciones por Correo',
        'Receive updates via email': 'Reciba actualizaciones por correo',
        'Push Notifications': 'Notificaciones Push',
        'Receive browser notifications': 'Reciba notificaciones en el navegador',
        'Profile updated successfully': 'Perfil actualizado con éxito',
        'Error updating profile': 'Error al actualizar perfil',
        'Passwords do not match': 'Las contraseñas no coinciden',
        'New password must be at least 6 characters': 'La nueva contraseña debe tener al menos 6 caracteres',
        'Password changed successfully!': '¡Contraseña cambiada con éxito!',
        'Error changing password': 'Error al cambiar contraseña',
        'Good morning': 'Buenos días',
        'Good afternoon': 'Buenas tardes',
        'Good evening': 'Buenas noches',
        'Continue your learning journey': 'Continúa tu viaje de aprendizaje',
        'days of streak!': 'días de racha!',
        'All': 'Todos',
        'Trending': 'Tendencias',
        'What do you want to share?': '¿Qué quieres compartir?',
        'Create Post': 'Crear Publicación',
        'Title (optional)': 'Título (opcional)',
        'What do you want to share with the community?': '¿Qué quieres compartir con la comunidad?',
        'Publish': 'Publicar',
        'No posts yet. Be the first to share!': 'No hay publicaciones aún. ¡Sé el primero en compartir!',
        'Popular': 'Popular',
        'No courses in progress.': 'No hay cursos en curso.',
        'Completed Courses': 'Cursos Completados',
        '100% Completed': '100% Completado',
        'Recommended': 'Recomendado',
        'Points Ranking': 'Ranking de Puntos',
        'No ranking available.': 'No hay ranking disponible.',
        'Your Achievements': 'Tus Logros',
        'No achievements yet.': 'Sin logros aún.',
        'Change Avatar': 'Cambiar Avatar',
        'Receive updates and reminders via WhatsApp': 'Recibir actualizaciones y recordatorios por WhatsApp',
        'Receive updates and newsletters via Email': 'Recibir actualizaciones y noticias por Correo',
        'Avatar updated': 'Avatar actualizado',
        'Failed to update avatar': 'Error al actualizar avatar',
        'Are you sure you want to delete this course?': '¿Estás seguro de que deseas eliminar este curso?',
        'Failed to delete course': 'Error al eliminar curso',
        'Start a post...': 'Iniciar una publicación...',
        'Posting in space': 'Publicando en el espacio',
        'Choose a space': 'Elegir un espacio',
        'Comments': 'Comentarios',
        'Write a comment...': 'Escribir un comentario...',
        'Send': 'Enviar',
        'No completed courses yet.': 'Aún no hay cursos completados.',
        'In Progress': 'En Progreso',
        'Community Feed': 'Muro de la Comunidad',
        'View all': 'Ver todos',
    },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('PT-BR');

    useEffect(() => {
        const savedLang = localStorage.getItem('language') as Language;
        if (savedLang) {
            setLanguage(savedLang);
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
