export const countries = [
    { name: "Brazil", code: "+55", flag: "🇧🇷" },
    { name: "United States", code: "+1", flag: "🇺🇸" },
    { name: "Portugal", code: "+351", flag: "🇵🇹" },
    { name: "Argentina", code: "+54", flag: "🇦🇷" },
    { name: "United Kingdom", code: "+44", flag: "🇬🇧" },
    { name: "Canada", code: "+1", flag: "🇨🇦" },
    { name: "Germany", code: "+49", flag: "🇩🇪" },
    { name: "France", code: "+33", flag: "🇫🇷" },
    { name: "Spain", code: "+34", flag: "🇪🇸" },
    { name: "Italy", code: "+39", flag: "🇮🇹" },
    { name: "Japan", code: "+81", flag: "🇯🇵" },
    { name: "China", code: "+86", flag: "🇨🇳" },
    { name: "India", code: "+91", flag: "🇮🇳" },
    { name: "Australia", code: "+61", flag: "🇦🇺" },
    { name: "Mexico", code: "+52", flag: "🇲🇽" },
    { name: "Russia", code: "+7", flag: "🇷🇺" },
    { name: "South Africa", code: "+27", flag: "🇿🇦" },
    { name: "Chile", code: "+56", flag: "🇨🇱" },
    { name: "Colombia", code: "+57", flag: "🇨🇴" },
    { name: "Peru", code: "+51", flag: "🇵🇪" },
];
